List<Map<String, dynamic>> reviewData = [
  {
    'id': 1,
    'title': '곤약 볶음밥',
    'description': '000 곤약 볶음밥 리뷰합니다.',
    'imageFile': '/',
    'tagKind': ['저칼로리', '0칼로리', '저당'],
    'like': 100,
    'comment': 100,
    'writer': '작성자',
    'creationDate': '2024-00-00',
    'brandSearch': '제조사',
    'productSearch': '제품명',
    'image': '/',
    'price': 10000,
    'calorie': "100kcal",
  },
  {
    'id': 2,
    'title': '곤약 볶음밥',
    'description': '000 곤약 볶음밥 리뷰합니다.',
    'imageFile': '/',
    'tagKind': ['저칼로리', '0칼로리', '저당'],
    'like': 100,
    'comment': 100,
    'writer': '작성자',
    'creationDate': '2024-00-00',
    'brandSearch': '제조사',
    'productSearch': '제품명',
    'image': '/',
    'price': 10000,
    'calorie': "100kcal",
  },
  {
    'id': 3,
    'title': '곤약 볶음밥',
    'description': '000 곤약 볶음밥 리뷰합니다.',
    'imageFile': '/',
    'tagKind': ['저칼로리', '0칼로리', '저당'],
    'like': 100,
    'comment': 100,
    'writer': '작성자',
    'creationDate': '2024-00-00',
    'brandSearch': '제조사',
    'productSearch': '제품명',
    'image': '/',
    'price': 10000,
    'calorie': "100kcal",
    
  },
  {
    'id': 4,
    'title': '곤약 볶음밥',
    'description': '000 곤약 볶음밥 리뷰합니다.',
    'imageFile': '/',
    'tagKind': ['저칼로리', '0칼로리', '저당'],
    'like': 100,
    'comment': 100,
    'writer': '작성자',
    'creationDate': '2024-00-00',
    'brandSearch': '제조사',
    'productSearch': '제품명',
    'image': '/',
    'price': 10000,
    'calorie': "100kcal",
    
  },
  {
    'id': 5,
    'title': '곤약 볶음밥',
    'description': '000 곤약 볶음밥 리뷰합니다.',
    'imageFile': '/',
    'tagKind': ['저칼로리', '0칼로리', '저당'],
    'like': 100,
    'comment': 100,
    'creationDate': '2024-00-00',
    'brandSearch': '제조사',
    'productSearch': '제품명',
    'image': '/',
    'price': 10000,
    'calorie': "100kcal",
  },
  {
    'id': 6,
    'title': '곤약 볶음밥',
    'description': '000 곤약 볶음밥 리뷰합니다.',
    'imageFile': '/',
    'tagKind': ['저칼로리', '0칼로리', '저당'],
    'like': 100,
    'comment': 100,
    'writer': '작성자',
    'creationDate': '2024-00-00',
    'brandSearch': '제조사',
    'productSearch': '제품명',
    'image': '/',
    'price': 10000,
    'calorie': "100kcal",
    
  },
  {
    'id': 7,
    'title': '곤약 볶음밥',
    'description': '000 곤약 볶음밥 리뷰합니다.',
    'imageFile': '/',
    'tagKind': ['저칼로리', '0칼로리', '저당'],
    'like': 100,
    'comment': 100,
    'writer': '작성자',
    'creationDate': '2024-00-00',
    'brandSearch': '제조사',
    'productSearch': '제품명',
    'image': '/',
    'price': 10000,
    'calorie': "100kcal",
    
  },
];
